import type { Company, FundingRound } from "./types";

export const companies: Company[] = [
  {
    slug: "tsla",
    ticker: "TSLA",
    name: "Tesla",
    isPublic: true,
    brandColor: "#CC0000",
    industry: "Automobile Manufacturers",
    sector: "Consumer Discretionary",
    founded: "2003",
    employees: "~140,000",
    about:
      "Tesla designs and manufactures electric vehicles, battery energy storage, and solar products. The company also develops autonomous driving software and has expanded into robotics and AI compute.",
  },
  {
    slug: "nvda",
    ticker: "NVDA",
    name: "NVIDIA",
    isPublic: true,
    brandColor: "#76B900",
    industry: "Semiconductors",
    sector: "Technology",
    founded: "1993",
    employees: "~36,000",
    about:
      "NVIDIA designs graphics processing units and AI accelerator chips that power gaming, data centers, and machine learning workloads across the industry.",
  },
  {
    slug: "msft",
    ticker: "MSFT",
    name: "Microsoft",
    isPublic: true,
    brandColor: "#00A4EF",
    industry: "Software Infrastructure",
    sector: "Technology",
    founded: "1975",
    employees: "~228,000",
    about:
      "Microsoft develops operating systems, productivity software, cloud infrastructure through Azure, and gaming hardware, with a growing investment in AI products.",
  },
  {
    slug: "meta",
    ticker: "META",
    name: "Meta Platforms",
    isPublic: true,
    brandColor: "#0866FF",
    industry: "Internet Content & Social Media",
    sector: "Technology",
    founded: "2004",
    employees: "~74,000",
    about:
      "Meta Platforms builds social networking apps including Facebook, Instagram, and WhatsApp, and is investing heavily in AI and virtual and augmented reality hardware.",
  },
  {
    slug: "amzn",
    ticker: "AMZN",
    name: "Amazon",
    isPublic: true,
    brandColor: "#FF9900",
    industry: "Internet Retail",
    sector: "Consumer Discretionary",
    founded: "1994",
    employees: "~1,550,000",
    about:
      "Amazon operates a global e-commerce marketplace alongside Amazon Web Services, the leading cloud computing platform, and a growing advertising and logistics business.",
  },
  {
    slug: "googl",
    ticker: "GOOGL",
    name: "Alphabet",
    isPublic: true,
    brandColor: "#4285F4",
    industry: "Internet Content & Information",
    sector: "Technology",
    founded: "1998",
    employees: "~180,000",
    about:
      "Alphabet is the parent company of Google, the dominant search and advertising platform, along with YouTube, Android, Google Cloud, and AI research through Google DeepMind.",
  },
  {
    slug: "aapl",
    ticker: "AAPL",
    name: "Apple",
    isPublic: true,
    brandColor: "#555555",
    industry: "Consumer Electronics",
    sector: "Technology",
    founded: "1976",
    employees: "~164,000",
    about:
      "Apple designs and sells consumer electronics, software, and services including the iPhone, Mac, iPad, and App Store, with a growing services segment spanning streaming, payments, and subscriptions.",
  },
  {
    slug: "amd",
    ticker: "AMD",
    name: "AMD",
    isPublic: true,
    brandColor: "#ED1C24",
    industry: "Semiconductors",
    sector: "Technology",
    founded: "1969",
    employees: "~26,000",
    about:
      "AMD designs CPUs and GPUs for data centers, gaming consoles, and PCs, and has become a leading supplier of AI accelerator chips that compete directly with NVIDIA in the data center market.",
  },
  {
    slug: "jpm",
    ticker: "JPM",
    name: "JPMorgan Chase",
    isPublic: true,
    brandColor: "#003087",
    industry: "Diversified Banks",
    sector: "Financials",
    founded: "1799",
    employees: "~310,000",
    about:
      "JPMorgan Chase is the largest U.S. bank by assets, operating across consumer banking, commercial banking, investment banking, asset management, and payments.",
  },
  {
    slug: "gs",
    ticker: "GS",
    name: "Goldman Sachs",
    isPublic: true,
    brandColor: "#6BA4DA",
    industry: "Capital Markets",
    sector: "Financials",
    founded: "1869",
    employees: "~46,000",
    about:
      "Goldman Sachs is a global investment bank providing advisory, securities, asset management, and consumer banking services to corporations, governments, and institutional investors.",
  },
  {
    slug: "jnj",
    ticker: "JNJ",
    name: "Johnson & Johnson",
    isPublic: true,
    brandColor: "#D3003F",
    industry: "Drug Manufacturers",
    sector: "Healthcare",
    founded: "1886",
    employees: "~132,000",
    about:
      "Johnson & Johnson develops pharmaceutical products and medical devices, with a focus on oncology, immunology, and neuroscience following its consumer health spinoff into Kenvue.",
  },
  {
    slug: "unh",
    ticker: "UNH",
    name: "UnitedHealth Group",
    isPublic: true,
    brandColor: "#002677",
    industry: "Healthcare Plans",
    sector: "Healthcare",
    founded: "1977",
    employees: "~440,000",
    about:
      "UnitedHealth Group operates the largest U.S. health insurance business (UnitedHealthcare) alongside Optum, a health services and data analytics platform serving payers, providers, and employers.",
  },
  {
    slug: "xom",
    ticker: "XOM",
    name: "ExxonMobil",
    isPublic: true,
    brandColor: "#C01933",
    industry: "Oil & Gas Integrated",
    sector: "Energy",
    founded: "1870",
    employees: "~62,000",
    about:
      "ExxonMobil is one of the world's largest publicly traded oil and gas companies, operating across exploration, production, refining, and chemicals, with growing investments in carbon capture and low-emission fuels.",
  },
  {
    slug: "cvx",
    ticker: "CVX",
    name: "Chevron",
    isPublic: true,
    brandColor: "#0072CE",
    industry: "Oil & Gas Integrated",
    sector: "Energy",
    founded: "1879",
    employees: "~40,000",
    about:
      "Chevron is a global integrated energy company engaged in oil and natural gas exploration, production, and refining, with operations in more than 180 countries and a growing portfolio in renewable energy.",
  },
  {
    slug: "wmt",
    ticker: "WMT",
    name: "Walmart",
    isPublic: true,
    brandColor: "#0071CE",
    industry: "Discount Stores",
    sector: "Consumer Staples",
    founded: "1962",
    employees: "~2,100,000",
    about:
      "Walmart is the world's largest retailer by revenue, operating supercenters, discount stores, and Sam's Club warehouse clubs, with a fast-growing e-commerce and advertising business.",
  },
  {
    slug: "cost",
    ticker: "COST",
    name: "Costco",
    isPublic: true,
    brandColor: "#E31837",
    industry: "Discount Stores",
    sector: "Consumer Staples",
    founded: "1983",
    employees: "~316,000",
    about:
      "Costco operates a chain of membership-only warehouse clubs selling groceries, electronics, apparel, and more in bulk at low margins, with membership fees driving the majority of its profit.",
  },
  {
    slug: "hd",
    ticker: "HD",
    name: "Home Depot",
    isPublic: true,
    brandColor: "#F96302",
    industry: "Home Improvement Retail",
    sector: "Consumer Discretionary",
    founded: "1978",
    employees: "~465,000",
    about:
      "Home Depot is the largest U.S. home improvement retailer, selling tools, building materials, and home products to both DIY consumers and professional contractors through over 2,300 stores.",
  },
  {
    slug: "cat",
    ticker: "CAT",
    name: "Caterpillar",
    isPublic: true,
    brandColor: "#FFD100",
    industry: "Farm & Heavy Construction Machinery",
    sector: "Industrials",
    founded: "1925",
    employees: "~113,000",
    about:
      "Caterpillar is the world's leading manufacturer of construction and mining equipment, diesel engines, and industrial gas turbines, with a large financial services arm supporting equipment purchases globally.",
  },
  {
    slug: "spacex",
    ticker: null,
    name: "SpaceX",
    isPublic: false,
    brandColor: "#005288",
    industry: "Aerospace & Defense",
    sector: "Industrials",
    founded: "2002",
    employees: "~13,000",
    about:
      "SpaceX designs, manufactures, and launches rockets and spacecraft, operating the Falcon 9, Falcon Heavy, and Starship vehicles alongside the Starlink satellite internet constellation.",
  },
  {
    slug: "openai",
    ticker: null,
    name: "OpenAI",
    isPublic: false,
    brandColor: "#412991",
    industry: "Artificial Intelligence",
    sector: "Technology",
    founded: "2015",
    employees: "~3,000",
    about:
      "OpenAI develops large language models and AI systems including GPT-4 and the o-series reasoning models, and operates ChatGPT, the fastest consumer product to reach 100 million users.",
  },
  {
    slug: "figure",
    ticker: null,
    name: "Figure AI",
    isPublic: false,
    brandColor: "#1A1A1A",
    industry: "Robotics",
    sector: "Technology",
    founded: "2022",
    employees: "~300",
    about:
      "Figure AI builds general-purpose humanoid robots designed to perform physical labor in warehouses and manufacturing plants, backed by NVIDIA, Microsoft, OpenAI, Amazon, and Samsung.",
  },
  {
    slug: "anthropic",
    ticker: null,
    name: "Anthropic",
    isPublic: false,
    brandColor: "#CC785C",
    industry: "Artificial Intelligence",
    sector: "Technology",
    founded: "2021",
    employees: "~2,000 (estimate)",
    about:
      "Anthropic is an AI safety and research company that builds Claude, a family of large language models, with a focus on making frontier AI systems reliable and interpretable.",
  },
];

export const fundingRounds: FundingRound[] = [
  { round: "Series A", date: "May 2021", amount: "$124M", valuation: "n/a", leadInvestor: "Jaan Tallinn" },
  { round: "Series B", date: "Apr 2022", amount: "$580M", valuation: "$4.1B", leadInvestor: "Sam Bankman-Fried" },
  { round: "Series C", date: "May 2023", amount: "$450M", valuation: "$4.1B", leadInvestor: "Spark Capital" },
  { round: "Strategic", date: "Sep 2023", amount: "Up to $4B", valuation: "n/a", leadInvestor: "Amazon" },
  { round: "Series D", date: "Jan 2024", amount: "$750M", valuation: "$18.4B", leadInvestor: "Menlo Ventures" },
  { round: "Series E", date: "Mar 2025", amount: "$3.5B", valuation: "$61.5B", leadInvestor: "Lightspeed Venture Partners" },
  { round: "Series F", date: "Sep 2025", amount: "$13B", valuation: "$183B", leadInvestor: "ICONIQ Capital" },
];

export function getCompanyByParam(param: string): Company | undefined {
  const value = param.toLowerCase();
  return companies.find(
    (c) => c.slug === value || c.ticker?.toLowerCase() === value
  );
}
